spring:
   application:
      name: "spring_validation"
   jpa:
      properties:
         hibernate:
            globally_quoted_identifiers: true
            show_sql: true
            format_sql: true
      open-in-view: false
      hibernate:
         ddl-auto: update
   datasource:
      url: jdbc:postgresql://127.0.0.1:5432/postgres
      driver-class-name: org.postgresql.Driver
      username: postgres
      password: sA#259979148307
logging:
   level:
      org:
         springframework:
            transaction:
               interceptor: trace
      root: INFO
   file:
      path: src/main/resources/logs
      name: src/main/resources/logs/logs.log
server:
   port: 8080

